Переписанный код + module4-task1
htmlacademy-javascript/1409557-keksobooking-21 pull request #4
Opened 2020-10-04 14:14 UTC by Mikalaus

2020-10-05 07:23 UTC, ademaro commented on js/main.js
> +  if (type === 'bungalow' && price < BUNGALOW_MIN_PRICE) {
вынести отдельно данные от логики...
```js
const MinPrice = {
  BUNGALOW: 0,
  FLAT: 1000,
  ...
}
```

2020-10-05 07:24 UTC, ademaro commented on js/main.js
> +    adFormPrice.placeholder = `${BUNGALOW_MIN_PRICE}`
и сюда пойдёт из перечисления

2020-10-05 07:26 UTC, ademaro commented on js/main.js
> +  adFormTimeOutOptions.forEach((item) => {
item на нормальное имя поменяй, слишком абстрактно тут и ниже

2020-10-05 07:27 UTC, ademaro commented on js/main.js
> +    if (item.value <= number && item.value !== '0' && number !== '100') {
тут данные так же вынеси из логики

2020-10-05 07:29 UTC, ademaro commented on js/main.js
> +    let left = obj.style.left = (parseInt(obj.style.left,10)) - 21;
числовые литералы — в константы

2020-10-05 07:31 UTC, ademaro requested changes
`out/*` — сначала всё удалить из репозитория, сделать коммит, потом добавить эту папку в гитинор. Зачем нам в проекте это?...

2020-10-06 01:02 UTC, Mikalaus commented on js/main.js
> +    if (item.value <= number && item.value !== '0' && number !== '100') {
Я в комменты вынесу, что надо это обсудить, прост там не совсем понятно как и что выносить в качестве 0 и 100. Это value кол-ва гостей и кол-во комнат, мне их отдельно находить через querySelector в начале и через .value в const выносить?

2020-10-09 11:49 UTC, merged